### ISSUE TITLE
Zip starter not working for certain URLs

### ISSUE THREAD

**Issue by mgrove** [edgi-govdata-archiving/archivers.space#66]
The zip starter seems to not work for some URLs and work for others. Here are some UUIDs for which the zip starter doesn't work for me on Firefox or Chrome (using Windows, although I tried to use Linux for several of them last night, and that didn't work either):

7115EDA4-34EF-4148-AA3F-0D2C72FF4BB7
77D88C3C-7C47-413A-BCA1-6CE19C237BED
FA38C827-D488-424D-92DE-BB17B553DD6F
555BAE6B-5B5C-4677-91D3-CD48F525FD70
FFB1A9E9-FDCB-49CF-BA33-FB8139B95C2C
40B56E61-11C5-42E9-B440-49E5B164A80C
3E1C57A2-0244-4CF4-A860-39CE2300AEDA
A69C90A4-B43E-4852-905F-5C72827E75FF
07B3C201-7620-43C9-BCF6-9ADD52B7E9F9
A9C4D3D3-DE86-4731-BB2C-902AE8DEB94B

Sometimes the server responds with an "unavailable" error, but usually it's a "bad request" error. At the time of this writing, all of these are in the Harvest section of the website, and I did check out each one before I tried to download the zip starter. Some of the links are broken, but others are not. Several of them have notes that indicate that other people have also had trouble downloading the zip starter. 

EDIT: I will add more UUIDs to the list as I discover them.

**Comment by b5** [comment]
@mgrove thanks so much for this clear outline of the problem.

Turns out all the urls mentioned are dead / broken links, which the [zip-starter](https://github.com/edgi-govdata-archiving/zip-starter) was reporting as an error & causing the failure. We've [adjusted the behavior of zip-starter](https://github.com/edgi-govdata-archiving/zip-starter/issues/6) to make this work.
